/// <reference types="vite/client" />

import type { JSX } from "@solidjs/web";
import { createRootRoute, HeadContent, Outlet, Scripts } from "@tanstack/solid-router";
import { Box } from "chakra-ui-solid";
import { onSettled } from "solid-js";
import { SiteHeader } from "~/components/layout/header";
import { NotFound } from "~/components/layout/not-found";
import { shellClass } from "~/components/layout/shell";
import { SiteGradientDefs } from "~/components/ui/logo";
import { SITE_DESCRIPTION, SITE_NAME } from "~/config";
import { colorModePrePaintScript, syncColorMode } from "~/lib/color-mode";
// This app's **own** Panda output, generated by `pnpm --filter @chakra-ui-solid/docs cssgen` from
// `panda.config.ts`. Not the repo's dev stylesheet — that one is generated from *our* source for
// the browser tests and Storybook, and importing it here would make the site stop being evidence
// that a consumer's build produces working CSS (`docs-site.md` §1.1).
import appCss from "../../styled-system/styles.css?url";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: SITE_NAME },
      { name: "description", content: SITE_DESCRIPTION },
    ],
    // The four-file icon set, and each of the four is a different consumer.
    //
    // `favicon.ico` is the legacy one and `sizes="any"` is what demotes it: a browser that
    // understands SVG then prefers `icon.svg`, and one that does not falls back to the `.ico`
    // instead of preferring it for having a declared size. Safari on iOS reads neither and uses
    // `apple-touch-icon` alone, which is why that file is a PNG on an opaque background — iOS
    // composites transparency against black rather than against the home screen.
    //
    // Android takes its home-screen icon from the manifest, so the two PNGs there are not
    // duplicates of the `.ico`; nothing else on the page can supply them.
    //
    // No `theme-color` pair sits above, and it is not an oversight: the head manager keys `meta` by
    // `name`, so the usual light/dark pair collapses to whichever is written last and the survivor
    // paints the wrong toolbar in the other mode. The manifest carries the one value instead.
    links: [
      { rel: "stylesheet", href: appCss },
      { rel: "icon", href: "/favicon.ico", sizes: "any" },
      { rel: "icon", href: "/icon.svg", type: "image/svg+xml" },
      { rel: "apple-touch-icon", href: "/apple-touch-icon.png", sizes: "180x180" },
      { rel: "manifest", href: "/site.webmanifest" },
    ],
  }),
  notFoundComponent: () => (
    <RootLayout>
      <NotFound />
    </RootLayout>
  ),
  component: () => (
    <RootLayout>
      <Outlet />
    </RootLayout>
  ),
});

function RootLayout(props: { children: JSX.Element }) {
  // The other half of the pre-paint script below: it wrote the class before the first paint, and
  // this publishes what it wrote to the one signal that reads it. `onSettled` — Solid 2.0's
  // client-only setup hook — rather than module scope, because hydration has to be finished before
  // the write lands on an attribute the server already rendered (`~/lib/color-mode`).
  onSettled(syncColorMode);

  return (
    <html lang="en" dir="ltr">
      <head>
        <HeadContent />
        {/*
          The colour-mode class, written before the first paint.

          This is not a flash-of-unstyled nicety. `@chakra-ui/panda-preset` gives its ~100 semantic
          colour tokens no base value — each is declared only inside `.light { … }` and
          `.dark { … }` — so a prerendered page that reaches the browser with neither class
          resolves every one of them to an undefined custom property and computes `transparent`.
          Without this script the page has **no colours at all** until JavaScript runs
          (`decisions-ledger.md` D-113).

          `innerHTML` rather than a text child because Solid escapes text in the SSR output, and an
          escaped script is a syntax error rather than a colour mode.
        */}
        <script innerHTML={colorModePrePaintScript} />
      </head>
      <body class={shellClass}>
        {/* Every bolt on the site fills from one of these three gradients (`~/components/ui/logo`). */}
        <SiteGradientDefs />
        <SiteHeader />
        {/* No footer here, and that is the point. The docs shell's sidebar and table of contents are
            sticky inside the article's flex row, so anything the root layout renders *below* that row
            is scroll the sticky columns cannot survive: the last ~190px of every docs page dragged
            both of them up off the screen, and on a one-screen page that was the only scroll there
            was. The footer belongs to the landing page, which has no sticky columns
            (`~/routes/index`). */}
        <Box as="main" flex="1">
          {props.children}
        </Box>
        <Scripts />
      </body>
    </html>
  );
}
