/// <reference types="vite/client" />

import type { JSX } from "@solidjs/web";
import { createRootRoute, HeadContent, Outlet, Scripts } from "@tanstack/solid-router";
import { Box } from "chakra-ui-solid";
import { shellClass } from "~/components/layout";
import { NotFound } from "~/components/not-found";
import { SiteGradientDefs } from "~/components/site/icons";
import { SiteFooter } from "~/components/site-footer";
import { SiteHeader } from "~/components/site-header";
import { SITE_DESCRIPTION, SITE_NAME } from "~/config";
import { colorModePrePaintScript } from "~/lib/color-mode";
// This app's **own** Panda output, generated by `pnpm --filter @chakra-ui-solid/docs cssgen` from
// `panda.config.ts`. Not the repo's dev stylesheet — that one is generated from *our* source for
// the browser tests and Storybook, and importing it here would make the site stop being evidence
// that a consumer's build produces working CSS (`docs-site.md` §1.1).
import appCss from "../../styled-system/styles.css?url";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: SITE_NAME },
      { name: "description", content: SITE_DESCRIPTION },
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      { rel: "icon", href: "/favicon.ico", sizes: "any" },
    ],
  }),
  notFoundComponent: () => (
    <RootLayout>
      <NotFound />
    </RootLayout>
  ),
  component: () => (
    <RootLayout>
      <Outlet />
    </RootLayout>
  ),
});

function RootLayout(props: { children: JSX.Element }) {
  return (
    <html lang="en" dir="ltr">
      <head>
        <HeadContent />
        {/*
          The colour-mode class, written before the first paint.

          This is not a flash-of-unstyled nicety. `@chakra-ui/panda-preset` gives its ~100 semantic
          colour tokens no base value — each is declared only inside `.light { … }` and
          `.dark { … }` — so a prerendered page that reaches the browser with neither class
          resolves every one of them to an undefined custom property and computes `transparent`.
          Without this script the page has **no colours at all** until JavaScript runs
          (`decisions-ledger.md` D-113).

          `innerHTML` rather than a text child because Solid escapes text in the SSR output, and an
          escaped script is a syntax error rather than a colour mode.
        */}
        <script innerHTML={colorModePrePaintScript} />
      </head>
      <body class={shellClass}>
        {/* Every bolt on the site fills from one of these three gradients (`~/components/site/icons`). */}
        <SiteGradientDefs />
        <SiteHeader />
        <Box as="main" flex="1">
          {props.children}
        </Box>
        <SiteFooter />
        <Scripts />
      </body>
    </html>
  );
}
