import type { FlexProperties } from "@chakra-ui-solid/styled-system/patterns";
import { flex } from "@chakra-ui-solid/styled-system/patterns";
import { type CssProp, chakra, composeCss, type HTMLChakraProps } from "@chakra-ui-solid/system";
import { type Component, merge, omit } from "solid-js";

export interface FlexOptions extends FlexProperties {
  /** Lay the children out inline, as `inline-flex` rather than `flex`. */
  inline?: boolean;
}

/** `direction` is displaced because CSS has a `direction` property, so it is already a style prop. */
export interface FlexProps extends Omit<HTMLChakraProps<"div">, "direction">, FlexOptions {}

const SHORTHANDS = [
  "direction",
  "align",
  "justify",
  "wrap",
  "basis",
  "grow",
  "shrink",
  "inline",
] as const;

/**
 * Flex — a Box that lays its children out with flexbox, with Chakra's seven shorthands
 * (`direction`, `align`, `justify`, `wrap`, `basis`, `grow`, `shrink`) on top of the full style
 * prop surface.
 *
 * The shorthand → property mapping is Panda's own `flex` **pattern**, reused rather than
 * re-implemented, and that is load-bearing rather than tidy. `direction="row"` is a *prop*: no
 * source file anywhere contains `flexDirection: "row"` for Panda to extract, so the rule can only
 * come from the consumer's own `<Flex direction="row">` — which their extractor maps through this
 * same pattern, because Panda's `flex` pattern claims the JSX name `Flex`. A hand-written
 * `align → alignItems` here would put one copy of the mapping in our runtime and a different one
 * in their build, and the two would agree until they didn't.
 *
 * `inline` is the exception the pattern has no answer for; its rule is pre-generated by the
 * preset's `staticCss`.
 */
export const Flex: Component<FlexProps> = (props) => {
  const elementProps = merge(omit(props, ...SHORTHANDS, "css"), {
    get css(): CssProp {
      const styles = flex.raw({
        direction: props.direction,
        align: props.align,
        justify: props.justify,
        wrap: props.wrap,
        basis: props.basis,
        grow: props.grow,
        shrink: props.shrink,
      });
      if (props.inline === true) {
        styles.display = "inline-flex";
      }
      return composeCss(styles, props.css);
    },
  });

  return <chakra.div {...elementProps} />;
};
