import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { Config } from "@pandacss/dev";

/**
 * `PandaPlugin` is imported by `@pandacss/dev` but not re-exported from it, and a consumer holding
 * only the peer dependency cannot resolve `@pandacss/types` — so the type is read off `Config`,
 * which is the one type that boundary does export.
 */
type Plugin = NonNullable<Config["plugins"]>[number];

const FILE_NAME = "chakra-system.ts";

/**
 * The module a consumer feeds to `<ChakraProvider>`, and the reason nothing here has to resolve a
 * path it cannot know: it sits **inside their outdir**, so `./css` and its three siblings are
 * ordinary relative imports in their own project, resolved identically by Vite, webpack, Vitest and
 * tsc. No alias, no `tsconfig#paths`, no bundler plugin.
 *
 * `chakra-ui-solid` rather than `@chakra-ui-solid/core`, where `createSystem` is declared: the
 * barrel re-exports it, and a package manager with an isolated `node_modules` — pnpm's default —
 * puts only the package a consumer installed on their resolution path.
 */
const SYSTEM_MODULE = `/* eslint-disable */
/**
 * The styled-system every chakra-ui-solid component under a \`<ChakraProvider>\` styles itself from.
 *
 * Generated by \`panda codegen\`. Every run rewrites it, so a change belongs in \`panda.config.ts\`.
 *
 * \`\`\`tsx
 * import { ChakraProvider } from "chakra-ui-solid";
 * import { system } from "./styled-system/chakra-system";
 *
 * <ChakraProvider value={system}>
 *   <App />
 * </ChakraProvider>
 * \`\`\`
 *
 * The class names on the element and the rules in your stylesheet come out of the same Panda run, so
 * a custom utility, an added variant, a renamed class or a hashed sheet agree by construction rather
 * than by both sides being configured the same way.
 */
import { createSystem } from "chakra-ui-solid";
import * as css from "./css";
import { isCssProperty } from "./jsx/is-valid-prop";
import * as patterns from "./patterns";
import * as recipes from "./recipes";
import { token } from "./tokens";

export const system = createSystem({ ...css, isCssProperty, token, patterns, recipes });
`;

/**
 * Writes `chakra-system.ts` into the directory Panda already owns and regenerates.
 *
 * Without it a consumer assembles the same imports by hand and re-checks them against every Panda
 * upgrade — and, once the types follow the config too, maintains a second file beside it that only
 * a generator can keep in step with what they wrote.
 *
 * `codegen:done` rather than `codegen:prepare`, which is where Panda lets a plugin hand it an
 * artifact to write: an artifact carries an `ArtifactId`, and that is a closed union of Panda's own
 * ids. This writes one file beside the ones Panda has just finished writing, using nothing about
 * Panda but its two documented hooks.
 */
export function systemModulePlugin(): Plugin {
  /** Where to write, because `codegen:done` carries only which artifacts changed. */
  let outdir: string | undefined;

  return {
    name: "chakra-ui-solid:system-module",
    hooks: {
      /**
       * `context:created`, not `config:resolved`, and the difference is measured rather than read
       * off the types: both hooks are handed a `UserConfig`, which declares `cwd` **required**, and
       * at `config:resolved` it is `undefined`. Panda fills it in on the way to the context, whose
       * hook is documented as carrying "the resolved config".
       */
      "context:created": ({ ctx }) => {
        outdir = resolve(ctx.config.cwd, ctx.config.outdir);
      },

      "codegen:done": () => {
        if (outdir === undefined) {
          return;
        }

        mkdirSync(outdir, { recursive: true });
        const path = join(outdir, FILE_NAME);
        // Identical bytes are not rewritten: a consumer's dev server watches this directory, and a
        // touched mtime on every `panda --watch` rebuild is a reload that changes nothing.
        if (existsSync(path) && readFileSync(path, "utf8") === SYSTEM_MODULE) {
          return;
        }
        writeFileSync(path, SYSTEM_MODULE);
      },
    },
  };
}
