import type { RecipeShape } from "./index";

/**
 * The 56 slot recipes. What a row means, and why these are typed out rather than read off the
 * loaded preset, is in `./index.ts`.
 *
 * **`swittch` is in here, misspelled, and every preset has to misspell it too.** Panda names the
 * generated function after the key, and `export const switch` is a syntax error — which is why
 * upstream's own generator renames it. Its `className` is the correctly spelled `switch`, so the
 * misspelling is confined to the key a preset author types (`roadmap.md` §1.3c).
 */
export const slotRecipeContract = {
  accordion: {
    className: "accordion",
    slots: ["root", "item", "itemTrigger", "itemContent", "itemIndicator", "itemBody"],
    variants: {
      variant: ["outline", "subtle", "enclosed", "plain"],
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  actionBar: {
    className: "action-bar",
    slots: ["positioner", "content", "separator", "selectionTrigger", "closeTrigger"],
    variants: {
      placement: ["bottom", "bottom-start", "bottom-end"],
    },
    defaultVariants: { placement: "bottom" },
  },
  alert: {
    className: "alert",
    slots: ["title", "description", "root", "indicator", "content"],
    variants: {
      status: ["info", "warning", "success", "error", "neutral"],
      inline: ["true", "false"],
      variant: ["subtle", "surface", "outline", "solid"],
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { status: "info", variant: "subtle", size: "md", inline: false },
  },
  avatar: {
    className: "avatar",
    slots: ["root", "image", "fallback"],
    variants: {
      size: ["full", "2xs", "xs", "sm", "md", "lg", "xl", "2xl"],
      variant: ["solid", "subtle", "outline"],
      shape: ["square", "rounded", "full"],
      borderless: ["true"],
    },
    defaultVariants: { size: "md", shape: "full", variant: "subtle" },
  },
  blockquote: {
    className: "blockquote",
    slots: ["root", "icon", "content", "caption"],
    variants: {
      justify: ["start", "center", "end"],
      variant: ["subtle", "solid", "plain"],
    },
    defaultVariants: { variant: "subtle", justify: "start" },
  },
  breadcrumb: {
    className: "breadcrumb",
    slots: ["link", "currentLink", "item", "list", "root", "ellipsis", "separator"],
    variants: {
      variant: ["underline", "plain"],
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { variant: "plain", size: "md" },
  },
  card: {
    className: "card",
    slots: ["root", "header", "body", "footer", "title", "description"],
    variants: {
      size: ["sm", "md", "lg"],
      variant: ["elevated", "outline", "subtle"],
    },
    defaultVariants: { variant: "outline", size: "md" },
  },
  carousel: {
    className: "carousel",
    slots: [
      "root",
      "itemGroup",
      "item",
      "control",
      "nextTrigger",
      "prevTrigger",
      "indicatorGroup",
      "indicator",
      "autoplayTrigger",
      "progressText",
      "progressText",
      "autoplayIndicator",
    ],
    variants: {},
    defaultVariants: {},
  },
  checkbox: {
    className: "checkbox",
    slots: ["root", "label", "control", "indicator", "group"],
    variants: {
      size: ["xs", "sm", "md", "lg"],
      variant: ["outline", "solid", "subtle"],
    },
    defaultVariants: { variant: "solid", size: "md" },
  },
  checkboxCard: {
    className: "checkbox-card",
    slots: ["root", "control", "label", "description", "addon", "indicator", "content"],
    variants: {
      size: ["sm", "md", "lg"],
      variant: ["surface", "subtle", "outline", "solid"],
      justify: ["start", "end", "center"],
      align: ["start", "end", "center"],
      orientation: ["vertical", "horizontal"],
    },
    defaultVariants: { size: "md", variant: "outline", align: "start", orientation: "horizontal" },
  },
  codeBlock: {
    className: "code-block",
    slots: [
      "root",
      "content",
      "title",
      "header",
      "footer",
      "control",
      "overlay",
      "code",
      "codeText",
      "copyTrigger",
      "copyIndicator",
      "collapseTrigger",
      "collapseIndicator",
      "collapseText",
    ],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  collapsible: {
    className: "collapsible",
    slots: ["root", "trigger", "content", "indicator"],
    variants: {},
    defaultVariants: {},
  },
  dataList: {
    className: "data-list",
    slots: ["root", "item", "itemLabel", "itemValue"],
    variants: {
      orientation: ["horizontal", "vertical"],
      size: ["sm", "md", "lg"],
      variant: ["subtle", "bold"],
    },
    defaultVariants: { size: "md", orientation: "vertical", variant: "subtle" },
  },
  datePicker: {
    className: "date-picker",
    slots: [
      "clearTrigger",
      "content",
      "control",
      "input",
      "label",
      "monthSelect",
      "nextTrigger",
      "positioner",
      "presetTrigger",
      "prevTrigger",
      "rangeText",
      "root",
      "table",
      "tableBody",
      "tableCell",
      "tableCellTrigger",
      "tableHead",
      "tableHeader",
      "tableRow",
      "trigger",
      "view",
      "viewControl",
      "viewTrigger",
      "yearSelect",
      "view",
      "valueText",
      "indicatorGroup",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg", "xl"],
      hideOutsideDays: ["true"],
      variant: ["outline", "subtle", "flushed"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  dialog: {
    className: "dialog",
    slots: [
      "trigger",
      "backdrop",
      "positioner",
      "content",
      "title",
      "description",
      "closeTrigger",
      "header",
      "body",
      "footer",
      "backdrop",
    ],
    variants: {
      placement: ["center", "top", "bottom"],
      scrollBehavior: ["inside", "outside"],
      size: ["xs", "sm", "md", "lg", "xl", "cover", "full"],
      motionPreset: [
        "scale",
        "slide-in-bottom",
        "slide-in-top",
        "slide-in-left",
        "slide-in-right",
        "none",
      ],
    },
    defaultVariants: {
      size: "md",
      scrollBehavior: "outside",
      placement: "top",
      motionPreset: "scale",
    },
  },
  drawer: {
    className: "drawer",
    slots: [
      "trigger",
      "backdrop",
      "positioner",
      "content",
      "title",
      "description",
      "closeTrigger",
      "header",
      "body",
      "footer",
      "backdrop",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg", "xl", "full"],
      placement: ["start", "end", "top", "bottom"],
      contained: ["true"],
    },
    defaultVariants: { size: "xs", placement: "end" },
  },
  editable: {
    className: "editable",
    slots: [
      "root",
      "area",
      "label",
      "preview",
      "input",
      "editTrigger",
      "submitTrigger",
      "cancelTrigger",
      "control",
      "textarea",
    ],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  emptyState: {
    className: "empty-state",
    slots: ["root", "content", "indicator", "title", "description"],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  field: {
    className: "field",
    slots: [
      "root",
      "errorText",
      "helperText",
      "input",
      "label",
      "select",
      "textarea",
      "requiredIndicator",
      "requiredIndicator",
    ],
    variants: {
      orientation: ["vertical", "horizontal"],
    },
    defaultVariants: { orientation: "vertical" },
  },
  fieldset: {
    className: "fieldset",
    slots: ["root", "errorText", "helperText", "legend", "content"],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  fileUpload: {
    className: "file-upload",
    slots: [
      "root",
      "dropzone",
      "item",
      "itemDeleteTrigger",
      "itemGroup",
      "itemName",
      "itemPreview",
      "itemPreviewImage",
      "itemSizeText",
      "label",
      "trigger",
      "clearTrigger",
      "itemContent",
      "dropzoneContent",
      "fileText",
    ],
    variants: {},
    defaultVariants: {},
  },
  hoverCard: {
    className: "hover-card",
    slots: ["arrow", "arrowTip", "trigger", "positioner", "content"],
    variants: {
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  list: {
    className: "list",
    slots: ["root", "item", "indicator"],
    variants: {
      variant: ["marker", "plain"],
      align: ["center", "start", "end"],
    },
    defaultVariants: { variant: "marker" },
  },
  listbox: {
    className: "listbox",
    slots: [
      "label",
      "input",
      "item",
      "itemText",
      "itemIndicator",
      "itemGroup",
      "itemGroupLabel",
      "content",
      "root",
      "valueText",
      "empty",
    ],
    variants: {
      variant: ["subtle", "solid", "plain"],
    },
    defaultVariants: { variant: "subtle" },
  },
  menu: {
    className: "menu",
    slots: [
      "arrow",
      "arrowTip",
      "content",
      "contextTrigger",
      "indicator",
      "item",
      "itemGroup",
      "itemGroupLabel",
      "itemIndicator",
      "itemText",
      "positioner",
      "separator",
      "trigger",
      "triggerItem",
      "itemCommand",
    ],
    variants: {
      variant: ["subtle", "solid"],
      size: ["sm", "md"],
    },
    defaultVariants: { size: "md", variant: "subtle" },
  },
  nativeSelect: {
    className: "native-select",
    slots: ["root", "field", "indicator"],
    variants: {
      variant: ["outline", "subtle", "plain", "ghost"],
      size: ["xs", "sm", "md", "lg", "xl"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  numberInput: {
    className: "number-input",
    slots: [
      "root",
      "label",
      "input",
      "control",
      "valueText",
      "incrementTrigger",
      "decrementTrigger",
      "scrubber",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg"],
      variant: ["outline", "subtle", "flushed"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  pinInput: {
    className: "pin-input",
    slots: ["root", "label", "input", "control"],
    variants: {
      size: ["2xs", "xs", "sm", "md", "lg", "xl", "2xl"],
      variant: ["outline", "subtle", "flushed"],
      attached: ["true"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  popover: {
    className: "popover",
    slots: [
      "arrow",
      "arrowTip",
      "anchor",
      "trigger",
      "indicator",
      "positioner",
      "content",
      "title",
      "description",
      "closeTrigger",
      "header",
      "body",
      "footer",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  progress: {
    className: "progress",
    slots: [
      "root",
      "label",
      "track",
      "range",
      "valueText",
      "view",
      "circle",
      "circleTrack",
      "circleRange",
    ],
    variants: {
      variant: ["outline", "subtle"],
      shape: ["square", "rounded", "full"],
      striped: ["true"],
      animated: ["true"],
      size: ["xs", "sm", "md", "lg", "xl"],
    },
    defaultVariants: { variant: "outline", size: "md", shape: "rounded" },
  },
  progressCircle: {
    className: "progress-circle",
    slots: [
      "root",
      "label",
      "track",
      "range",
      "valueText",
      "view",
      "circle",
      "circleTrack",
      "circleRange",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg", "xl"],
    },
    defaultVariants: { size: "md" },
  },
  radioCard: {
    className: "radio-card",
    slots: [
      "root",
      "label",
      "item",
      "itemText",
      "itemControl",
      "indicator",
      "itemAddon",
      "itemIndicator",
      "itemContent",
      "itemDescription",
    ],
    variants: {
      size: ["sm", "md", "lg"],
      variant: ["surface", "subtle", "outline", "solid"],
      justify: ["start", "end", "center"],
      align: ["start", "end", "center"],
      orientation: ["vertical", "horizontal"],
    },
    defaultVariants: { size: "md", variant: "outline", align: "start", orientation: "horizontal" },
  },
  radioGroup: {
    className: "radio-group",
    slots: [
      "root",
      "label",
      "item",
      "itemText",
      "itemControl",
      "indicator",
      "itemAddon",
      "itemIndicator",
    ],
    variants: {
      variant: ["outline", "subtle", "solid"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "solid" },
  },
  ratingGroup: {
    className: "rating-group",
    slots: ["root", "label", "item", "control", "itemIndicator"],
    variants: {
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  scrollArea: {
    className: "scroll-area",
    slots: ["root", "viewport", "content", "scrollbar", "thumb", "corner"],
    variants: {
      variant: ["hover", "always"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "hover" },
  },
  segmentGroup: {
    className: "segment-group",
    slots: ["root", "label", "item", "itemText", "itemControl", "indicator"],
    variants: {
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  select: {
    className: "select",
    slots: [
      "label",
      "positioner",
      "trigger",
      "indicator",
      "clearTrigger",
      "item",
      "itemText",
      "itemIndicator",
      "itemGroup",
      "itemGroupLabel",
      "list",
      "content",
      "root",
      "control",
      "valueText",
      "indicatorGroup",
    ],
    variants: {
      variant: ["outline", "subtle", "ghost"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  combobox: {
    className: "combobox",
    slots: [
      "root",
      "clearTrigger",
      "content",
      "control",
      "input",
      "item",
      "itemGroup",
      "itemGroupLabel",
      "itemIndicator",
      "itemText",
      "label",
      "list",
      "positioner",
      "trigger",
      "empty",
      "indicatorGroup",
      "empty",
    ],
    variants: {
      variant: ["outline", "subtle", "flushed"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  slider: {
    className: "slider",
    slots: [
      "root",
      "label",
      "thumb",
      "valueText",
      "track",
      "range",
      "control",
      "markerGroup",
      "marker",
      "draggingIndicator",
      "markerIndicator",
      "markerLabel",
    ],
    variants: {
      size: ["sm", "md", "lg"],
      variant: ["outline", "solid"],
      orientation: ["vertical", "horizontal"],
    },
    defaultVariants: { size: "md", variant: "outline", orientation: "horizontal" },
  },
  splitter: {
    className: "splitter",
    slots: [
      "root",
      "panel",
      "resizeTrigger",
      "resizeTriggerIndicator",
      "resizeTriggerSeparator",
      "resizeTriggerIndicator",
    ],
    variants: {},
    defaultVariants: {},
  },
  stat: {
    className: "stat",
    slots: ["root", "label", "helpText", "valueText", "valueUnit", "indicator"],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  steps: {
    className: "steps",
    slots: [
      "root",
      "list",
      "item",
      "trigger",
      "indicator",
      "separator",
      "content",
      "title",
      "description",
      "nextTrigger",
      "prevTrigger",
      "progress",
    ],
    variants: {
      orientation: ["vertical", "horizontal"],
      variant: ["solid", "subtle"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { size: "md", variant: "solid", orientation: "horizontal" },
  },
  swittch: {
    className: "switch",
    slots: ["root", "label", "control", "thumb", "indicator"],
    variants: {
      variant: ["solid", "raised"],
      size: ["xs", "sm", "md", "lg"],
    },
    defaultVariants: { variant: "solid", size: "md" },
  },
  table: {
    className: "table",
    slots: ["root", "header", "body", "row", "columnHeader", "cell", "footer", "caption"],
    variants: {
      interactive: ["true"],
      stickyHeader: ["true"],
      striped: ["true"],
      showColumnBorder: ["true"],
      variant: ["line", "outline"],
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { variant: "line", size: "md" },
  },
  tabs: {
    className: "tabs",
    slots: ["root", "trigger", "list", "content", "contentGroup", "indicator"],
    variants: {
      fitted: ["true"],
      justify: ["start", "center", "end"],
      size: ["sm", "md", "lg"],
      variant: ["line", "subtle", "enclosed", "outline", "plain"],
    },
    defaultVariants: { size: "md", variant: "line" },
  },
  tag: {
    className: "tag",
    slots: ["root", "label", "closeTrigger", "startElement", "endElement"],
    variants: {
      size: ["sm", "md", "lg", "xl"],
      variant: ["subtle", "solid", "outline", "surface"],
    },
    defaultVariants: { size: "md", variant: "surface" },
  },
  tagsInput: {
    className: "tags-input",
    slots: [
      "root",
      "label",
      "control",
      "input",
      "clearTrigger",
      "item",
      "itemPreview",
      "itemInput",
      "itemText",
      "itemDeleteTrigger",
    ],
    variants: {
      size: ["xs", "sm", "md", "lg"],
      variant: ["outline", "subtle", "flushed"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  toast: {
    className: "toast",
    slots: ["root", "title", "description", "indicator", "closeTrigger", "actionTrigger"],
    variants: {},
    defaultVariants: {},
  },
  tooltip: {
    className: "tooltip",
    slots: ["trigger", "arrow", "arrowTip", "positioner", "content"],
    variants: {},
    defaultVariants: {},
  },
  status: {
    className: "status",
    slots: ["root", "indicator"],
    variants: {
      size: ["sm", "md", "lg"],
    },
    defaultVariants: { size: "md" },
  },
  timeline: {
    className: "timeline",
    slots: [
      "root",
      "item",
      "content",
      "separator",
      "indicator",
      "connector",
      "title",
      "description",
    ],
    variants: {
      variant: ["subtle", "solid", "outline", "plain"],
      showLastSeparator: ["true", "false"],
      size: ["sm", "md", "lg", "xl"],
    },
    defaultVariants: { size: "md", variant: "solid", showLastSeparator: false },
  },
  colorPicker: {
    className: "colorPicker",
    slots: [
      "root",
      "label",
      "control",
      "trigger",
      "positioner",
      "content",
      "area",
      "areaThumb",
      "valueText",
      "areaBackground",
      "channelSlider",
      "channelSliderLabel",
      "channelSliderTrack",
      "channelSliderThumb",
      "channelSliderValueText",
      "channelInput",
      "transparencyGrid",
      "swatchGroup",
      "swatchTrigger",
      "swatchIndicator",
      "swatch",
      "eyeDropperTrigger",
      "formatTrigger",
      "formatSelect",
      "view",
      "channelText",
    ],
    variants: {
      size: ["2xs", "xs", "sm", "md", "lg", "xl", "2xl"],
      variant: ["outline", "subtle"],
    },
    defaultVariants: { size: "md", variant: "outline" },
  },
  qrCode: {
    className: "qr-code",
    slots: ["root", "frame", "pattern", "overlay", "downloadTrigger"],
    variants: {
      size: ["2xs", "xs", "sm", "md", "lg", "xl", "2xl", "full"],
    },
    defaultVariants: { size: "md" },
  },
  treeView: {
    className: "tree-view",
    slots: [
      "branch",
      "branchContent",
      "branchControl",
      "branchIndentGuide",
      "branchIndicator",
      "branchText",
      "branchTrigger",
      "item",
      "itemIndicator",
      "itemText",
      "label",
      "nodeCheckbox",
      "nodeRenameInput",
      "root",
      "tree",
    ],
    variants: {
      size: ["md", "sm", "xs"],
      variant: ["subtle", "solid"],
      animateContent: ["true"],
    },
    defaultVariants: { size: "md", variant: "subtle" },
  },
  marquee: {
    className: "marquee",
    slots: ["root", "viewport", "content", "edge", "item"],
    variants: {},
    defaultVariants: {},
  },
  floatingPanel: {
    className: "floating-panel",
    slots: [
      "trigger",
      "positioner",
      "content",
      "header",
      "body",
      "title",
      "resizeTrigger",
      "dragTrigger",
      "stageTrigger",
      "closeTrigger",
      "control",
    ],
    variants: {},
    defaultVariants: {},
  },
} as const satisfies Record<string, RecipeShape>;
