import { mount } from "@chakra-ui-solid/internal-test-utils";
import { afterEach, describe, expect, it } from "vitest";
import { Box } from "../box";
import consumerStylesheet from "./__fixtures__/consumer/consumer.css?raw";

/**
 * The half of the styling seam that a green suite over our own stylesheet cannot see: **does an
 * override in a consumer's `panda.config.ts` reach our components?**
 *
 * The two claims are genuinely different. Our own tests prove our pipeline computes the right class
 * names and our sheet gives them the right rules. This one proves the architecture underneath that:
 * the consumer's Panda run produces the stylesheet, our published runtime produces the class names,
 * and the two meet on the name alone. Nothing in this library participates in an override — which
 * is exactly why it needs a test rather than an argument.
 *
 * `consumer.css` is generated by a second, real Panda run over
 * `__fixtures__/consumer/panda.config.ts`, which spreads `chakraConfig()` and overrides two tokens
 * to values nothing could produce by coincidence: `spacing.4` → `99px` and `colors.red.500` →
 * `#00ff00`.
 */

let mounted: { container: HTMLElement; dispose: () => void } | undefined;
let injected: HTMLStyleElement | undefined;

afterEach(() => {
  mounted?.dispose();
  mounted = undefined;
  injected?.remove();
  injected = undefined;
});

function renderBox(ui: () => ReturnType<typeof Box>): HTMLElement {
  mounted = mount(ui);
  const element = mounted.container.firstElementChild;
  if (!(element instanceof HTMLElement)) {
    throw new Error("expected Box to render one element");
  }
  return element;
}

/** Appended last, so its token block wins on order within the same cascade layer. */
function applyConsumerStylesheet(): void {
  injected = document.createElement("style");
  injected.textContent = consumerStylesheet;
  document.head.append(injected);
}

describe("a consumer's panda.config.ts override", () => {
  it("changes what Box renders, through the class names our runtime already computed", () => {
    const element = renderBox(() => <Box p="4" bg="red.500" />);

    // Our sheet first: `spacing.4` is `1rem` and `red.500` is Chakra's.
    expect(getComputedStyle(element).padding).toBe("16px");
    expect(getComputedStyle(element).backgroundColor).toBe("rgb(239, 68, 68)");

    applyConsumerStylesheet();

    // Same element, same computed class names, different stylesheet.
    expect(getComputedStyle(element).padding).toBe("99px");
    expect(getComputedStyle(element).backgroundColor).toBe("rgb(0, 255, 0)");
  });

  it("carries a rule for a shorthand only our preset's alias table makes extractable", () => {
    // `gapX` is one of the 17 Chakra shorthands Panda does not ship. The consumer's fixture source
    // writes `<Box gapX="4">`, and their Panda run only emits a rule for it because our preset —
    // which their config pulled in through `chakraConfig()` — taught Panda the name.
    const element = renderBox(() => <Box display="flex" gapX="4" />);
    applyConsumerStylesheet();
    expect(getComputedStyle(element).columnGap).toBe("99px");
  });
});
