import { createComponentContext } from "@chakra-ui-solid/core";

/**
 * What a control reads off the {@link InputGroup} above it — whether an overlay is drawn over each
 * of its edges, and therefore whether its text needs to be pushed clear of one.
 *
 * Accessors rather than booleans: a group whose `startElement` arrives from a signal has to repaint
 * the control's padding, and a snapshot read here would freeze it at whatever it was when the
 * control mounted.
 */
export interface InputGroupContextValue {
  /** Whether an element is drawn over the leading edge of the control. */
  hasStartElement: () => boolean;
  /** Whether an element is drawn over the trailing edge of the control. */
  hasEndElement: () => boolean;
}

/**
 * The two style props a control contributes for itself, both of which may be absent.
 */
export interface InputGroupPadding {
  paddingInlineStart?: string | undefined;
  paddingInlineEnd?: string | undefined;
}

/**
 * The padding that clears an overlay, as **fixed literals** — the whole reason the offsets ride
 * inline custom properties rather than being interpolated into the string.
 *
 * `--input-height` is published by the *control's own* size variant, so the `calc()` has to evaluate
 * in the control's scope; `--input-group-*-offset` is written by the group and inherits down to it.
 * Interpolating the offset instead (Chakra's `` `calc(var(--input-height) - ${startOffset})` ``)
 * would make the value a template literal, which no `staticCss` row can pre-generate and no
 * extractor can find — the class would be emitted and the rule behind it would not exist
 * (`CLAUDE.md`, *The hazard: silent unstyling*). These two strings are pre-generated by the
 * `paddingInlineStart` / `paddingInlineEnd` rows in `packages/panda-preset/src/preset.ts` and have
 * to stay character-for-character identical to them.
 */
const START_PADDING = "calc(var(--input-height) - var(--input-group-start-offset, 0px))";
const END_PADDING = "calc(var(--input-height) - var(--input-group-end-offset, 0px))";

/**
 * Non-strict, and the third member is the point: a `<Input>` on its own page is not a mistake, so a
 * control has to be able to read "there is no group" rather than throw. Nothing outside this
 * directory needs the strict reader, which is why it is skipped rather than exported.
 *
 * The module imports **only core**, so `input.tsx` and `native-select.tsx` can import it by path
 * without an import cycle through the `input-group` barrel — `field-context.ts` is the same shape,
 * and `input.tsx` already reaches for that one the same way.
 */
export const [InputGroupProvider, , useOptionalInputGroupContext] =
  createComponentContext<InputGroupContextValue>("InputGroup");

/**
 * The opt-in a control adds to take its padding from the group around it.
 *
 * Chakra clones the child and spreads `...children.props` last so a consumer's own `ps` still wins;
 * a Solid control reads a context and places the result **lowest** in its own props chain, which is
 * the same precedence expressed where Solid can express it. Outside a group it contributes nothing
 * at all, so a control the group does not know about keeps its recipe's padding rather than
 * resolving `calc(var(--input-height) - …)` against an undeclared variable and collapsing to `0`.
 *
 * Call it from the control's body — it reads context — and hand the accessor to `mergeProps` as the
 * first source:
 *
 * ```ts
 * const groupPadding = useInputGroupPadding();
 * const merged = mergeProps(groupPadding, …, props);
 * ```
 */
export function useInputGroupPadding(): () => InputGroupPadding {
  const group = useOptionalInputGroupContext();

  // Both keys are always present, `undefined` included. `renderStyled` partitions style props from
  // DOM props **once**, off the key set the merged bag reports at construction, so a key that only
  // appears later is never recognised as a style prop; and the key *order* is what makes a
  // consumer's `ps` beat this one, since Panda resolves the shorthand and the longhand to the same
  // property and the last key in the object wins. An `undefined` value emits no class.
  return () => ({
    paddingInlineStart: group?.hasStartElement() ? START_PADDING : undefined,
    paddingInlineEnd: group?.hasEndElement() ? END_PADDING : undefined,
  });
}
