import { mkdtempSync, readFileSync, rmSync, statSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { defineChakraConfig } from "../config";

/**
 * The file a consumer's Panda run writes into their own outdir, and the reason nothing in this
 * design resolves a path it cannot know: `chakra-system.ts` lands **beside** the artifacts it
 * imports, so `./css` and its siblings are ordinary relative imports in the consumer's project.
 *
 * The hooks are driven directly rather than by shelling out to `panda codegen`, which would make
 * this a test of Panda. What Panda actually does with the two hooks is asserted where a real run
 * happens: the consumer fixture under `packages/chakra-ui-solid`, whose generated module is the one
 * its browser tests render against.
 */

const cwd = mkdtempSync(join(tmpdir(), "chakra-system-"));

afterAll(() => {
  rmSync(cwd, { recursive: true, force: true });
});

function generateInto(outdir: string): string {
  const plugin = (defineChakraConfig({ include: [], outdir }).plugins ?? []).find(
    (candidate) => candidate.name === "chakra-ui-solid:system-module",
  );
  if (plugin === undefined) {
    throw new Error("defineChakraConfig no longer appends the system-module plugin");
  }

  // `cwd` and `outdir` are the whole of what the plugin reads off the context, and `cwd` is the
  // reason it reads them *here*: `config:resolved` is handed the same `UserConfig` type with `cwd`
  // still undefined on it.
  plugin.hooks?.["context:created"]?.({
    ctx: { config: { cwd, outdir } } as never,
    logger: {} as never,
  });
  plugin.hooks?.["codegen:done"]?.({ changed: undefined });

  return join(cwd, outdir, "chakra-system.ts");
}

describe("the system module a consumer's Panda run generates", () => {
  const source = readFileSync(generateInto("styled-system"), "utf8");

  it("assembles the system from the artifacts sitting beside it", () => {
    // Relative, and that is the whole distribution story: no alias, no `tsconfig#paths`, no bundler
    // plugin, and the same resolution under Vite, webpack, Vitest and node.
    expect(source).toContain('import * as css from "./css";');
    expect(source).toContain('import { isCssProperty } from "./jsx/is-valid-prop";');
    expect(source).toContain('import * as patterns from "./patterns";');
    expect(source).toContain('import { token } from "./tokens";');
    expect(source).toContain(
      "export const system = createSystem({ ...css, isCssProperty, token, patterns });",
    );
  });

  it("imports `createSystem` from the package a consumer installed", () => {
    // It is declared in `@chakra-ui-solid/core` and re-exported by the barrel. A generated file
    // naming `core` would not resolve at all under pnpm's isolated `node_modules`, where only the
    // installed package is on the resolution path.
    expect(source).toContain('import { createSystem } from "chakra-ui-solid";');
    expect(source).not.toContain("@chakra-ui-solid/core");
  });

  it("says it is generated, and where to make the change instead", () => {
    expect(source).toContain("Generated by `panda codegen`");
    expect(source).toContain("a change belongs in `panda.config.ts`");
  });

  it("writes into whatever outdir the config named", () => {
    expect(readFileSync(generateInto("styled-system-app"), "utf8")).toBe(source);
  });

  it("restores a file someone edited", () => {
    const path = generateInto("styled-system-edited");
    writeFileSync(path, "export const system = undefined;\n");

    expect(readFileSync(generateInto("styled-system-edited"), "utf8")).toBe(source);
  });

  it("does not touch a file it would have written identically", () => {
    // A consumer's dev server watches this directory, so a rewritten mtime on every `--watch`
    // rebuild is a reload that changes nothing. The timestamp is backdated rather than compared
    // across two runs, which could land in the same millisecond and pass on a real rewrite.
    const path = generateInto("styled-system-watched");
    const backdated = new Date(Date.now() - 60_000);
    utimesSync(path, backdated, backdated);

    generateInto("styled-system-watched");

    expect(statSync(path).mtimeMs).toBe(backdated.getTime());
  });
});
