import { chakra } from "@chakra-ui-solid/system";
import type { ComponentProps } from "@solidjs/web";

/**
 * Center — a flex container that puts its child in the middle on both axes.
 *
 * The whole component is one `chakra()` call: an element plus a **style config** (`base` +
 * `variants`), which Panda reads out of this file at build time and turns into rules. The runtime
 * only recomputes the class names those rules were generated under.
 *
 * `inline` is a runtime toggle — nothing in a consumer's source literally writes
 * `display: inline-flex` — so the rule is pre-generated by the preset's `staticCss`
 * (`display: [… "inline-flex" …]`). Without that entry the prop would silently do nothing.
 */
export const Center = chakra("div", {
  base: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  variants: {
    inline: {
      true: { display: "inline-flex" },
    },
  },
});

export type CenterProps = ComponentProps<typeof Center>;
